# Generated by Django 4.1 on 2022-09-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('place_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reviews', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('place_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
