# Generated by Django 4.0.6 on 2022-09-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_categorias_plato_restaurantes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='FotoPlato/'),
        ),
    ]
