# Generated by Django 4.0.6 on 2022-09-24 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_plato_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.restaurantes'),
        ),
    ]
