# Generated by Django 4.0.6 on 2022-10-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_plato_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
