# Generated by Django 4.1 on 2022-11-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_usuarios_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='location',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
